apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=     # base64 encoded value of 'password'
  MYSQL_USER: dXNlcg==                  # base64 encoded value of 'user'
  MYSQL_PASSWORD: cGFzc3dvcmQ=          # base64 encoded value of 'password'
  MYSQL_DATABASE: ZGJuYW1l              # base64 encoded value of 'dbname'
