stages:
  - build
  - test
  - deploy

variables:
  FRONTEND_IMAGE: my-frontend-image
  BACKEND_IMAGE: my-backend-image
  CI_REGISTRY: registry.sananetco.com

before_script:
  - echo "Starting CI/CD Pipeline"

build-frontend:
  stage: build
  script:
    - docker login $CI_REGISTRY -u admin -p 123@qwe
    - docker build -t $CI_REGISTRY/$FRONTEND_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY/$FRONTEND_IMAGE:$CI_COMMIT_SHA
  tags:
    - test

test:
  stage: test
  script:
    - echo "Testing stage - add your tests here"
  tags:
    - test

deploy:
  stage: deploy
  image: dtzar/helm-kubectl:latest
  script:
    - echo "Deploying to Kubernetes"
    - mkdir -p ~/.kube
    - echo "$KUBE_CONFIG" > ~/.kube/config
    - whoami && pwd
    - helm install my-fullstack-app ./deploy --set image.repository=$CI_REGISTRY/$FRONTEND_IMAGE --set image.tag=$CI_COMMIT_SHA --kubeconfig ~/.kube/config
  tags:
    - test
  only:
    - main
