apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: core
  name: get-pods-services-sa-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "serviceaccounts"]
  verbs: ["get", "list"]
