apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany  # This access mode allows multiple nodes to read and write
  nfs:
    path: /exported/path
    server: <NFS_SERVER_IP>
