global:
  smtp_from: "monitoring@gmail.com"
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_auth_username: "monitoring@gmail.com"
  smtp_auth_identity:  "monitoring@gmail.com"
  smtp_auth_password: "zxpohhekragqcldi"


route:
  receiver: 'discord'
  group_by: ['alertname', 'cluster']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
  - match:
      severity: info
    receiver: info
  - match:
      severity: default
    receiver: mail
receivers:
- name: info
  email_configs:
  - to: monitoring@gmail.com
  webhook_configs:
  - url: http://172.18.0.1:9094
    send_resolved: true
- name: mail
  email_configs:
  - to: monitoring@gmail.com


