---
- name: Create a new user
  user:
    name: "{{ new_username }}"
    password: "{{ user_password | password_hash('sha512') }}"
    state: present
    shell: /bin/bash
    createhome: yes

- name: Add the user to sudoers file
  lineinfile:
    path: "{{ sudoers_file }}"
    line: "{{ new_username }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
  when: "'{{ new_username }} ALL=(ALL) NOPASSWD: ALL' not in lookup('file', sudoers_file)"

